import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ChildModeHeader } from '@/components/child-ui';
import { Card, PageHeader, PageShell } from '@/components/playmap-ui';
import type { PlayCategory } from '@/domain/play-category';
import { playmapTheme as theme } from '@/theme/playmap-theme';
const choices: readonly { label: string; category: PlayCategory | 'anything'; tone: 'sage' | 'peach' | 'yellow' | 'lavender' }[] = [{ label: 'Something quiet', category: 'quiet', tone: 'sage' }, { label: 'Something active', category: 'active', tone: 'peach' }, { label: 'Build something', category: 'building', tone: 'yellow' }, { label: 'Make something', category: 'creative', tone: 'lavender' }, { label: 'Pretend', category: 'pretend', tone: 'peach' }, { label: 'Something sensory', category: 'sensory', tone: 'sage' }, { label: 'Play by myself', category: 'independent', tone: 'lavender' }, { label: 'Play together', category: 'together', tone: 'yellow' }, { label: 'Play inside', category: 'indoor', tone: 'sage' }, { label: 'Play outside', category: 'outdoor', tone: 'peach' }, { label: 'Show me anything', category: 'anything', tone: 'yellow' }];
export default function ChildCategoriesRoute() { return <PageShell child><ChildModeHeader onBack={() => router.replace('/child/home')} /><PageHeader eyebrow="CHOOSE A PLAY TYPE" title="What sounds good?" subtitle="Pick one kind of play." /><View style={styles.grid}>{choices.map((choice) => <Pressable key={choice.category} accessibilityLabel={choice.label} accessibilityRole="button" onPress={() => router.push({ pathname: '/child/toy-suggestions', params: { category: choice.category } })} style={({ pressed }) => [styles.item, pressed && styles.pressed]}><Card tone={choice.tone} style={styles.card}><Text style={styles.label}>{choice.label}</Text><Text accessible={false} style={styles.arrow}>›</Text></Card></Pressable>)}</View></PageShell>; }
const styles = StyleSheet.create({ grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, item: { flexGrow: 1, flexBasis: 260, maxWidth: 460 }, card: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 82 }, label: { color: theme.colors.primaryText, fontFamily: 'Georgia', fontSize: 20, fontWeight: '700' }, arrow: { color: theme.colors.sageAction, fontSize: 30 }, pressed: { opacity: 0.76 } });
