import { router } from 'expo-router';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { BackButton } from '@/components/onboarding-controls';
import { ChildButton } from '@/components/child-ui';
import type { PlayCategory } from '@/domain/play-category';
import { playmapTheme as theme, screenContentStyle } from '@/theme/playmap-theme';
const choices: readonly { label: string; category: PlayCategory | 'anything'; icon: string; tint: string }[] = [{ label: 'Something Quiet', category: 'quiet', icon: '☁', tint: theme.colors.surfaceMint }, { label: 'Something Active', category: 'active', icon: '☀', tint: theme.colors.surfacePeach }, { label: 'Build Something', category: 'building', icon: '▦', tint: theme.colors.surfaceYellow }, { label: 'Make Something', category: 'creative', icon: '✿', tint: '#F7E6E7' }, { label: 'Pretend', category: 'pretend', icon: '◡', tint: theme.colors.surfaceSage }, { label: 'Something Sensory', category: 'sensory', icon: '✦', tint: theme.colors.surfaceLavender }, { label: 'Play by Myself', category: 'independent', icon: '♡', tint: theme.colors.surfaceMint }, { label: 'Play Together', category: 'together', icon: '♧', tint: theme.colors.surfaceYellow }, { label: 'Play Inside', category: 'indoor', icon: '⌂', tint: theme.colors.surfaceSage }, { label: 'Play Outside', category: 'outdoor', icon: '☼', tint: '#E7F1F3' }, { label: 'Show Me Anything', category: 'anything', icon: '✧', tint: theme.colors.surfacePeach }];
export default function ChildCategoriesRoute() { return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.container}><BackButton onPress={() => router.back()} /><Text style={styles.eyebrow}>CHOOSE A PLAY TYPE</Text><Text accessibilityRole="header" style={styles.title}>What sounds good?</Text><Text style={styles.subtitle}>Pick one way to play.</Text><View style={styles.choices}>{choices.map((choice) => <View key={choice.category} style={styles.choice}><ChildButton label={`${choice.icon}  ${choice.label}`} tint={choice.tint} onPress={() => router.push({ pathname: '/child/toy-suggestions', params: { category: choice.category } })} /></View>)}</View></ScrollView>; }
const styles = StyleSheet.create({ container: { ...screenContentStyle, backgroundColor: theme.colors.childBackground, flexGrow: 1, gap: 10 }, eyebrow: { color: theme.colors.coralDark, fontSize: 12, fontWeight: '800', letterSpacing: 1.4 }, title: { color: theme.colors.primary, fontFamily: 'Georgia', fontSize: 36, fontWeight: '700', lineHeight: 44 }, subtitle: { color: theme.colors.secondaryText, fontSize: 17, marginBottom: 10 }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, choice: { flexBasis: '46%', flexGrow: 1, minWidth: 150 }, });
