import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { StyleSheet, Text } from 'react-native';
import { ChildModeHeader } from '@/components/child-ui';
import { Card, ImageTile, LoadingState, PageHeader, PageShell, PrimaryButton } from '@/components/playmap-ui';
import { initializeDatabase } from '@/database/client';
import { getActivePlaySession, type ActivePlaySession } from '@/repositories/play-sessions-repository';
import { getActiveChildProfile } from '@/repositories/child-profiles-repository';
export default function CurrentToyRoute() { const [session, setSession] = useState<ActivePlaySession | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { initializeDatabase().then(async (database) => getActivePlaySession(database, (await getActiveChildProfile(database)).id)).then(setSession).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Could not load the current toy.')).finally(() => setLoading(false)); }, []); if (loading) return <PageShell child scroll={false}><ChildModeHeader onBack={() => router.replace('/child/home')} /><LoadingState label="Loading your toy…" /></PageShell>; if (error || !session?.toy) return <PageShell child><ChildModeHeader onBack={() => router.replace('/child/home')} /><PageHeader eyebrow="CURRENT TOY" title="My Current Toy" subtitle="See the toy that is out for play." /><Card><Text>{error ?? 'No toy is active right now.'}</Text></Card></PageShell>; const toy = session.toy; return <PageShell child><ChildModeHeader onBack={() => router.replace('/child/home')} /><PageHeader eyebrow="CURRENT TOY" title={toy.name} subtitle={`${session.childName} is playing with this now.`} /><Card tone="sage" style={styles.toyCard}><ImageTile size={220} uri={toy.imageUri} /><Text style={styles.location}>{toy.roomName} · {toy.storageSpotName}</Text></Card><PrimaryButton label="I’m done playing" onPress={() => router.push('/child/cleanup')} /></PageShell>; }
const styles = StyleSheet.create({ toyCard: { alignItems: 'center', alignSelf: 'center', maxWidth: 520, width: '100%' }, location: { fontSize: 17, fontWeight: '700' } });
