import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, ErrorStateCard, LoadingState, PageShell } from '@/components/playmap-ui';
import { initializeDatabase } from '@/database/client';
import { getActivePlaySession } from '@/repositories/play-sessions-repository';
import { getSettings } from '@/repositories/settings-repository';
import { getActiveChildProfile } from '@/repositories/child-profiles-repository';
import { playmapTheme as theme } from '@/theme/playmap-theme';

export default function ChildHomeRoute() {
  const [nickname, setNickname] = useState<string | null>(null); const [hasActive, setHasActive] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { initializeDatabase().then(async (db) => { const [profile, settings] = await Promise.all([getActiveChildProfile(db), getSettings(db)]); const active = await getActivePlaySession(db, profile.id); setNickname(profile.name ?? settings.childNickname); setHasActive(active !== null); }).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Could not load Child Mode.')).finally(() => setLoading(false)); }, []);
  if (loading) return <PageShell child scroll={false}><LoadingState label="Getting PlayMap ready…" /></PageShell>;
  if (error) return <PageShell child><ErrorStateCard message={error} /></PageShell>;
  return <PageShell child><View style={styles.hero}><Text style={styles.hello}>Hi{nickname ? `, ${nickname}` : ''}</Text><Text accessibilityRole="header" style={styles.title}>What feels fun today?</Text><View style={styles.garden}><View style={styles.hill} /><View style={styles.sun} /><View style={styles.leafOne} /><View style={styles.leafTwo} /></View></View><View style={styles.actions}><ChildChoice title="Find a toy" detail="Choose what sounds good" tone="sage" onPress={() => router.push('/child/categories')} /><ChildChoice title="Surprise me" detail="Let PlayMap choose" tone="yellow" onPress={() => router.push({ pathname: '/child/toy-suggestions', params: { category: 'anything', surprise: '1' } })} /><ChildChoice disabled={!hasActive} title="My current toy" detail={hasActive ? 'See what you are playing with' : 'Nothing is playing right now'} tone="peach" onPress={() => router.push('/child/current-toy')} /></View><Pressable accessibilityRole="button" onPress={() => router.push('/child/parent-return')} style={styles.parent}><Text style={styles.parentText}>Grown-up area</Text></Pressable></PageShell>;
}
function ChildChoice({ title, detail, tone, onPress, disabled }: { title: string; detail: string; tone: 'sage' | 'yellow' | 'peach'; onPress(): void; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [pressed && styles.pressed, disabled && styles.disabled]}><Card tone={tone}><View style={styles.choiceRow}><View><Text style={styles.choiceTitle}>{title}</Text><Text style={styles.choiceDetail}>{detail}</Text></View><Text accessible={false} style={styles.arrow}>›</Text></View></Card></Pressable>; }
const styles = StyleSheet.create({ hero: { gap: 7 }, hello: { color: theme.colors.primaryText, fontSize: 17, fontWeight: '800' }, title: { color: theme.colors.primaryText, fontFamily: 'Georgia', fontSize: 38, fontWeight: '700', lineHeight: 45, maxWidth: 390 }, garden: { backgroundColor: theme.colors.surfaceMint, borderRadius: 24, height: 132, marginTop: 10, overflow: 'hidden', position: 'relative' }, hill: { backgroundColor: theme.colors.surfaceSage, borderRadius: 150, bottom: -68, height: 165, left: -30, position: 'absolute', width: '125%' }, sun: { backgroundColor: theme.colors.surfaceYellow, borderRadius: 30, height: 54, position: 'absolute', right: 32, top: 25, width: 54 }, leafOne: { backgroundColor: theme.colors.sageAction, borderRadius: 28, height: 70, left: 56, position: 'absolute', top: 43, transform: [{ rotate: '-30deg' }], width: 25 }, leafTwo: { backgroundColor: theme.colors.coralAction, borderRadius: 26, height: 55, left: 91, position: 'absolute', top: 64, transform: [{ rotate: '34deg' }], width: 22 }, actions: { gap: 10 }, choiceRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, choiceTitle: { color: theme.colors.primaryText, fontFamily: 'Georgia', fontSize: 24, fontWeight: '700' }, choiceDetail: { color: theme.colors.secondaryText, fontSize: 16, marginTop: 4 }, arrow: { color: theme.colors.primaryText, fontSize: 34 }, parent: { alignItems: 'center', minHeight: 48, justifyContent: 'center' }, parentText: { color: theme.colors.secondaryText, fontSize: 15, fontWeight: '700', textDecorationLine: 'underline' }, pressed: { opacity: 0.78 }, disabled: { backgroundColor: theme.colors.disabled, borderRadius: theme.radii.card } });
