/**
 * PlayMap's visual language. Keep product decisions here so screens and
 * components do not grow competing palettes or measurements.
 */
export const playmapTheme = {
  colors: {
    backgroundCream: '#FFF9F0',
    surface: '#FFFEFB',
    surfacePeach: '#FCE7DC',
    surfaceSage: '#E4EFE5',
    surfaceMint: '#E1F2EC',
    surfaceYellow: '#FFF2CC',
    surfaceLavender: '#EEE8F3',
    surfaceBlush: '#F7E6E7',
    surfaceSky: '#E7F1F3',
    coralAction: '#A94F3F',
    sageAction: '#5E8F7E',
    primaryText: '#3F4A43',
    secondaryText: '#69756E',
    mutedText: '#69756E',
    border: '#E6DCCF',
    error: '#A74742',
    errorSoft: '#FBE9E7',
    success: '#4F7D5D',
    successSoft: '#E2EFE4',
    warning: '#7A5A16',
    warningSoft: '#FFF2CC',
    disabled: '#D8DDD8',
    disabledText: '#59635D',
    focus: '#3F7363',
    white: '#FFFFFF',

    // Compatibility aliases for existing screens during the visual refactor.
    background: '#FFF9F0',
    childBackground: '#F2F8F2',
    elevatedSurface: '#FFFFFF',
    surfaceWarm: '#FFF1E7',
    surfaceCool: '#EAF3EC',
    text: '#3F4A43',
    muted: '#849087',
    peach: '#F7C6AF',
    peachSoft: '#FCE7DC',
    sage: '#9AB79E',
    sageSoft: '#E4EFE5',
    mint: '#A9D3C3',
    mintSoft: '#E1F2EC',
    yellow: '#F4D58B',
    yellowSoft: '#FFF2CC',
    lavender: '#CFC3DC',
    lavenderSoft: '#EEE8F3',
    coral: '#A94F3F',
    coralDark: '#A94F3F',
    primary: '#5E8F7E',
    primarySoft: '#E1F2EC',
    danger: '#A74742',
    photoFallback: '#F2E9DC',
  },
  typography: {
    display: { fontSize: 38, lineHeight: 46, fontWeight: '700' as const },
    pageTitle: { fontSize: 32, lineHeight: 40, fontWeight: '700' as const },
    sectionTitle: { fontSize: 22, lineHeight: 29, fontWeight: '700' as const },
    body: { fontSize: 17, lineHeight: 25, fontWeight: '400' as const },
    supporting: { fontSize: 14, lineHeight: 20, fontWeight: '400' as const },
    label: { fontSize: 15, lineHeight: 20, fontWeight: '700' as const },
    button: { fontSize: 17, lineHeight: 22, fontWeight: '700' as const },
    caption: { fontSize: 12, lineHeight: 17, fontWeight: '600' as const },
  },
  // Short aliases are retained for current callers.
  type: { display: 38, title: 32, childTitle: 36, section: 22, body: 17, small: 14, button: 17 },
  spacing: { 4: 4, 8: 8, 12: 12, 16: 16, 20: 20, 24: 24, 32: 32, 40: 40, xxs: 4, xs: 8, sm: 12, md: 16, lg: 20, xl: 24, xxl: 32, xxxl: 40 },
  radii: { small: 10, medium: 16, large: 22, pill: 999, card: 26, sm: 10, md: 16, lg: 22, xl: 30 },
  measurements: { minimumTouchTarget: 44, inputHeight: 54, primaryButtonHeight: 56, cardPadding: 20, screenHorizontalPadding: 20, pageMaxWidth: 960, formMaxWidth: 680, toyImageAspectRatio: 1.12 },
  sizes: { button: 56, childButton: 72, input: 54 },
  shadows: {
    card: { boxShadow: '0px 4px 16px rgba(89,72,52,0.08)', elevation: 2 } as const,
  },
  images: { toyCard: 1.12, hero: 1.25, upload: 1.65 },
} as const;

export const screenContentStyle = {
  alignSelf: 'center' as const,
  maxWidth: 920,
  paddingHorizontal: playmapTheme.measurements.screenHorizontalPadding,
  paddingTop: playmapTheme.spacing[24],
  paddingBottom: 56,
  width: '100%' as const,
};
