import { ActivityIndicator, Image, Pressable, StyleSheet, Text, TextInput, View, type ImageSourcePropType, type PressableProps, type StyleProp, type TextInputProps, type ViewStyle } from 'react-native';
import type { ReactNode } from 'react';
import { playmapTheme as theme } from '@/theme/playmap-theme';

type ButtonProps = Omit<PressableProps, 'children' | 'style'> & { label: string; accessibilityLabel?: string; style?: StyleProp<ViewStyle> };

export function ScreenContainer({ children, child = false }: { children: ReactNode; child?: boolean }) {
  return <View style={[styles.screen, child && styles.childScreen]}>{children}</View>;
}

export function PageHeader({ title, subtitle, eyebrow, action }: { title: string; subtitle?: string; eyebrow?: string; action?: ReactNode }) {
  return <View style={styles.pageHeader}>{action ? <View style={styles.headerRow}><View style={styles.headerCopy}>{eyebrow && <Text style={styles.eyebrow}>{eyebrow}</Text>}<Text accessibilityRole="header" style={styles.pageTitle}>{title}</Text>{subtitle && <Text style={styles.body}>{subtitle}</Text>}</View>{action}</View> : <>{eyebrow && <Text style={styles.eyebrow}>{eyebrow}</Text>}<Text accessibilityRole="header" style={styles.pageTitle}>{title}</Text>{subtitle && <Text style={styles.body}>{subtitle}</Text>}</>}</View>;
}

export function SectionHeading({ title, supporting, action }: { title: string; supporting?: string; action?: ReactNode }) {
  return <View style={styles.sectionHeading}>{<View style={styles.headerRow}><View style={styles.headerCopy}><Text accessibilityRole="header" style={styles.sectionTitle}>{title}</Text>{supporting && <Text style={styles.supporting}>{supporting}</Text>}</View>{action}</View>}</View>;
}

function ActionButton({ label, kind, accessibilityLabel, style, ...props }: ButtonProps & { kind: 'primary' | 'secondary' | 'destructive' }) {
  return <Pressable accessibilityLabel={accessibilityLabel ?? label} accessibilityRole="button" {...props} style={({ pressed }) => [styles.button, styles[`${kind}Button`], props.disabled && styles.disabled, pressed && !props.disabled && styles.pressed, style]}><Text style={[styles.buttonText, styles[`${kind}Text`]]}>{label}</Text></Pressable>;
}

export function PrimaryButton(props: ButtonProps) { return <ActionButton {...props} kind="primary" />; }
export function SecondaryButton(props: ButtonProps) { return <ActionButton {...props} kind="secondary" />; }
export function DestructiveButton(props: ButtonProps) { return <ActionButton {...props} kind="destructive" />; }

export function PastelNavigationCard({ title, description, icon, tint = theme.colors.surfaceSage, onPress, disabled }: { title: string; description?: string; icon?: string; tint?: string; onPress(): void; disabled?: boolean }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.navigationCard, { backgroundColor: tint }, disabled && styles.disabled, pressed && !disabled && styles.pressed]}><Text style={styles.cardIcon}>{icon}</Text><View style={styles.cardCopy}><Text style={styles.cardTitle}>{title}</Text>{description && <Text style={styles.supporting}>{description}</Text>}</View><Text accessibilityElementsHidden style={styles.chevron}>›</Text></Pressable>;
}

export function StatCard({ value, label }: { value: string | number; label: string }) { return <View style={styles.statCard}><Text style={styles.statValue}>{value}</Text><Text style={styles.caption}>{label}</Text></View>; }

export function RoundedTextInput({ label, error, ...props }: TextInputProps & { label?: string; error?: string | null }) {
  return <View style={styles.field}>{label && <Text style={styles.label}>{label}</Text>}<TextInput {...props} accessibilityLabel={props.accessibilityLabel ?? label} placeholderTextColor={theme.colors.mutedText} style={[styles.input, error && styles.inputError, props.style]} />{error !== undefined && <Text accessibilityLiveRegion="polite" style={styles.errorText}>{error ?? ''}</Text>}</View>;
}

export function RoundedSelect({ label, value, placeholder = 'Select an option', onPress, accessibilityLabel }: { label?: string; value?: string; placeholder?: string; onPress(): void; accessibilityLabel?: string }) {
  return <Pressable accessibilityLabel={accessibilityLabel ?? label} accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.select, pressed && styles.pressed]}>{label && <Text style={styles.label}>{label}</Text>}<View style={styles.selectRow}><Text style={[styles.selectValue, !value && styles.placeholder]}>{value ?? placeholder}</Text><Text style={styles.selectChevron}>⌄</Text></View></Pressable>;
}

export function FilterChip({ label, selected, onPress }: { label: string; selected?: boolean; onPress(): void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={({ pressed }) => [styles.chip, selected && styles.selectedChip, pressed && styles.pressed]}><Text style={[styles.chipText, selected && styles.selectedChipText]}>{selected ? '✓ ' : ''}{label}</Text></Pressable>; }
export function CategoryChip(props: { label: string; selected?: boolean; onPress(): void }) { return <FilterChip {...props} />; }

export function ToggleRow({ label, description, value, onValueChange }: { label: string; description?: string; value: boolean; onValueChange(value: boolean): void }) {
  return <Pressable accessibilityRole="switch" accessibilityState={{ checked: value }} onPress={() => onValueChange(!value)} style={styles.toggleRow}><View style={styles.cardCopy}><Text style={styles.label}>{label}</Text>{description && <Text style={styles.supporting}>{description}</Text>}</View><View style={[styles.toggle, value && styles.toggleOn]}><View style={[styles.toggleKnob, value && styles.toggleKnobOn]} /></View></Pressable>;
}

export function SegmentedControl<T extends string | number | boolean>({ options, value, onChange, accessibilityLabel = 'Options' }: { options: readonly T[]; value: T; onChange(value: T): void; accessibilityLabel?: string }) {
  return <View accessibilityLabel={accessibilityLabel} accessibilityRole="radiogroup" style={styles.segmented}>{options.map((option) => { const selected = option === value; return <Pressable key={String(option)} accessibilityRole="radio" accessibilityState={{ selected }} onPress={() => onChange(option)} style={[styles.segment, selected && styles.segmentSelected]}><Text style={[styles.segmentText, selected && styles.segmentSelectedText]}>{String(option)}</Text></Pressable>; })}</View>;
}

export function EmptyStateCard({ title, message, action }: { title: string; message: string; action?: ReactNode }) { return <View style={styles.stateCard}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.body}>{message}</Text>{action}</View>; }
export function ErrorStateCard({ message, action }: { message: string; action?: ReactNode }) { return <View accessibilityLiveRegion="polite" style={[styles.stateCard, styles.errorCard]}><Text style={styles.errorTitle}>Something went wrong</Text><Text style={styles.body}>{message}</Text>{action}</View>; }
export function LoadingState({ label = 'Loading…' }: { label?: string }) { return <View accessibilityLiveRegion="polite" style={styles.loading}><ActivityIndicator color={theme.colors.sageAction} /><Text style={styles.supporting}>{label}</Text></View>; }

export function ToyImage({ uri, source, accessibilityLabel = 'Toy photo' }: { uri?: string | null; source?: ImageSourcePropType; accessibilityLabel?: string }) {
  return uri || source ? <Image accessibilityIgnoresInvertColors accessibilityLabel={accessibilityLabel} source={source ?? { uri: uri ?? undefined }} style={styles.toyImage} /> : <View accessibilityLabel={`${accessibilityLabel} unavailable`} style={[styles.toyImage, styles.imageFallback]}><Text style={styles.supporting}>Photo unavailable</Text></View>;
}

export function ToyCard({ title, location, uri, action, onPress }: { title: string; location?: string; uri?: string | null; action?: string; onPress?: () => void }) {
  const content = <><ToyImage uri={uri} /><View style={styles.toyCardBody}><Text style={styles.cardTitle}>{title}</Text>{location && <Text style={styles.supporting}>{location}</Text>}{action && <Text style={styles.cardAction}>{action}</Text>}</View></>;
  return onPress ? <Pressable accessibilityRole="button" accessibilityLabel={title} onPress={onPress} style={({ pressed }) => [styles.toyCard, pressed && styles.pressed]}>{content}</Pressable> : <View style={styles.toyCard}>{content}</View>;
}

export function LocationChip({ label }: { label: string }) { return <View style={styles.locationChip}><Text style={styles.locationText}>⌖ {label}</Text></View>; }
export function ChildActionCard(props: { title: string; description: string; icon?: string; tint?: string; onPress(): void; disabled?: boolean }) { return <PastelNavigationCard {...props} description={props.description} />; }
export function StepIndicator({ steps, current }: { steps: readonly string[]; current: number }) { return <View accessibilityLabel={`Step ${current + 1} of ${steps.length}`} style={styles.steps}>{steps.map((step, index) => <View key={step} style={styles.step}><View style={[styles.stepDot, index <= current && styles.stepDotActive]}><Text style={styles.stepNumber}>{index + 1}</Text></View><Text style={[styles.caption, index === current && styles.stepLabelActive]}>{step}</Text></View>)}</View>; }
export function BottomNavigation({ items, selected, onSelect }: { items: readonly string[]; selected: string; onSelect(item: string): void }) { return <View style={styles.bottomNav}>{items.map((item) => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: selected === item }} onPress={() => onSelect(item)} style={styles.navItem}><Text style={[styles.navText, selected === item && styles.navTextSelected]}>{item}</Text></Pressable>)}</View>; }

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.backgroundCream }, childScreen: { backgroundColor: '#F2F8F2' },
  pageHeader: { gap: 8, marginBottom: theme.spacing[24] }, headerRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 16 }, headerCopy: { flex: 1, gap: 5 }, eyebrow: { color: theme.colors.coralDark, fontSize: 12, fontWeight: '800', letterSpacing: 1.5 }, pageTitle: { color: theme.colors.primaryText, fontFamily: 'Georgia', ...theme.typography.pageTitle }, sectionHeading: { marginBottom: theme.spacing[12] }, sectionTitle: { color: theme.colors.primaryText, fontFamily: 'Georgia', ...theme.typography.sectionTitle }, body: { color: theme.colors.secondaryText, ...theme.typography.body }, supporting: { color: theme.colors.secondaryText, ...theme.typography.supporting }, label: { color: theme.colors.primaryText, ...theme.typography.label }, caption: { color: theme.colors.mutedText, ...theme.typography.caption },
  button: { alignItems: 'center', borderRadius: theme.radii.large, justifyContent: 'center', minHeight: theme.measurements.minimumTouchTarget, paddingHorizontal: theme.spacing[20] }, primaryButton: { ...theme.shadows.card, backgroundColor: theme.colors.coralAction, minHeight: theme.measurements.primaryButtonHeight }, secondaryButton: { backgroundColor: theme.colors.surfaceMint, borderColor: theme.colors.sageAction, borderWidth: 1 }, destructiveButton: { backgroundColor: theme.colors.surface, borderColor: theme.colors.error, borderWidth: 1 }, buttonText: { textAlign: 'center', ...theme.typography.button }, primaryText: { color: theme.colors.white }, secondaryText: { color: theme.colors.sageAction }, destructiveText: { color: theme.colors.error }, disabled: { opacity: 0.48 }, pressed: { opacity: 0.78 },
  navigationCard: { ...theme.shadows.card, alignItems: 'center', borderColor: 'rgba(100,90,75,0.08)', borderRadius: theme.radii.card, borderWidth: 1, flexDirection: 'row', gap: 16, minHeight: 96, padding: theme.measurements.cardPadding }, cardIcon: { fontSize: 30, textAlign: 'center', width: 42 }, cardCopy: { flex: 1, gap: 4 }, cardTitle: { color: theme.colors.primaryText, fontFamily: 'Georgia', fontSize: 19, fontWeight: '700', lineHeight: 25 }, chevron: { color: theme.colors.secondaryText, fontSize: 30 }, statCard: { alignItems: 'center', backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radii.medium, borderWidth: 1, flex: 1, gap: 2, minHeight: 74, justifyContent: 'center', padding: theme.spacing[8] }, statValue: { color: theme.colors.primaryText, fontSize: 22, fontWeight: '700' },
  field: { gap: 6 }, input: { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radii.medium, borderWidth: 1, color: theme.colors.primaryText, fontSize: 17, minHeight: theme.measurements.inputHeight, paddingHorizontal: theme.spacing[16] }, inputError: { borderColor: theme.colors.error }, errorText: { color: theme.colors.error, minHeight: 17, ...theme.typography.caption }, select: { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radii.medium, borderWidth: 1, minHeight: theme.measurements.inputHeight, padding: theme.spacing[12] }, selectRow: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'space-between', marginTop: 3 }, selectValue: { color: theme.colors.primaryText, flex: 1, fontSize: 17 }, placeholder: { color: theme.colors.mutedText }, selectChevron: { color: theme.colors.sageAction, fontSize: 21 },
  chip: { alignItems: 'center', backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radii.pill, borderWidth: 1, justifyContent: 'center', minHeight: theme.measurements.minimumTouchTarget, paddingHorizontal: theme.spacing[12] }, selectedChip: { backgroundColor: theme.colors.surfaceMint, borderColor: theme.colors.sageAction, borderWidth: 2 }, chipText: { color: theme.colors.secondaryText, ...theme.typography.caption }, selectedChipText: { color: theme.colors.sageAction }, segmented: { backgroundColor: theme.colors.surfaceSage, borderRadius: theme.radii.pill, flexDirection: 'row', padding: 4 }, segment: { alignItems: 'center', borderRadius: theme.radii.pill, flex: 1, justifyContent: 'center', minHeight: theme.measurements.minimumTouchTarget, paddingHorizontal: 8 }, segmentSelected: { backgroundColor: theme.colors.surface, ...theme.shadows.card }, segmentText: { color: theme.colors.secondaryText, fontSize: 14, fontWeight: '600' }, segmentSelectedText: { color: theme.colors.sageAction, fontWeight: '800' },
  toggleRow: { alignItems: 'center', backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radii.medium, borderWidth: 1, flexDirection: 'row', gap: 16, minHeight: 64, paddingHorizontal: theme.spacing[16], paddingVertical: theme.spacing[12] }, toggle: { backgroundColor: theme.colors.disabled, borderRadius: theme.radii.pill, height: 30, justifyContent: 'center', padding: 3, width: 52 }, toggleOn: { backgroundColor: theme.colors.sageAction }, toggleKnob: { backgroundColor: theme.colors.white, borderRadius: theme.radii.pill, height: 24, width: 24 }, toggleKnobOn: { alignSelf: 'flex-end' }, stateCard: { ...theme.shadows.card, backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radii.card, borderWidth: 1, gap: 10, padding: theme.measurements.cardPadding }, errorCard: { backgroundColor: theme.colors.errorSoft, borderColor: theme.colors.error }, errorTitle: { color: theme.colors.error, fontSize: 18, fontWeight: '700' }, loading: { alignItems: 'center', flex: 1, gap: 12, justifyContent: 'center', padding: theme.spacing[24] },
  toyCard: { ...theme.shadows.card, backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderRadius: theme.radii.card, borderWidth: 1, flex: 1, minWidth: 150, overflow: 'hidden' }, toyImage: { aspectRatio: theme.measurements.toyImageAspectRatio, backgroundColor: theme.colors.surfacePeach, width: '100%' }, imageFallback: { alignItems: 'center', justifyContent: 'center' }, toyCardBody: { gap: 7, minHeight: 100, padding: theme.spacing[12] }, cardAction: { color: theme.colors.sageAction, fontSize: 14, fontWeight: '700' }, locationChip: { alignSelf: 'flex-start', backgroundColor: theme.colors.surfaceSage, borderRadius: theme.radii.pill, paddingHorizontal: theme.spacing[12], paddingVertical: theme.spacing[8] }, locationText: { color: theme.colors.sageAction, ...theme.typography.caption }, steps: { flexDirection: 'row', justifyContent: 'space-between' }, step: { alignItems: 'center', flex: 1, gap: 6 }, stepDot: { alignItems: 'center', backgroundColor: theme.colors.surfaceSage, borderRadius: theme.radii.pill, height: 32, justifyContent: 'center', width: 32 }, stepDotActive: { backgroundColor: theme.colors.sageAction }, stepNumber: { color: theme.colors.primaryText, fontSize: 14, fontWeight: '800' }, stepLabelActive: { color: theme.colors.sageAction, fontWeight: '800' }, bottomNav: { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderTopWidth: 1, flexDirection: 'row', paddingBottom: 8, paddingTop: 8 }, navItem: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: theme.measurements.minimumTouchTarget }, navText: { color: theme.colors.mutedText, fontSize: 12, fontWeight: '600' }, navTextSelected: { color: theme.colors.sageAction, fontWeight: '800' },
});
