import { HmacInstallationCredentialSigner, LocalDevelopmentStorage, resetLocalDevelopmentStorageForTests } from './durable-control';
import { DurableToyAnalysisService } from './durable-toy-analysis-service';
import { MockToyAnalysisProvider } from './mock-provider';

const image = { mediaType: 'image/jpeg' as const, byteLength: 100, mockReference: 'clear_toy' as const };
const id = (n: number) => `11111111-1111-4111-8111-${String(n).padStart(12, '0')}`;
async function fixture() { const storage = new LocalDevelopmentStorage(); const signer = new HmacInstallationCredentialSigner('test-secret'); const installationId = 'ins_1234567890abcdef123456789012345678'; const createdAt = new Date().toISOString(); await storage.installations.create({ installationId, createdAt, lastSeenAt: createdAt, status: 'active', credentialVersion: 1, betaAllowance: 10, betaUsed: 0, lifetimeSuccessfulAnalyses: 0, monthlySuccessfulAnalyses: 0, monthlyPeriodKey: createdAt.slice(0, 7) }); return { storage, signer, token: signer.issue(installationId, createdAt) }; }

describe('durable AI controls', () => {
  beforeEach(() => resetLocalDevelopmentStorageForTests());
  it('issues and verifies versioned credentials and rejects tampering', async () => { const { signer, token } = await fixture(); expect(signer.verify(token)).toMatchObject({ installationId: expect.stringMatching(/^ins_/) }); expect(signer.verify(`${token}x`)).toBeUndefined(); });
  it('persists successful quota and returns installation-scoped cached results', async () => { const { storage, signer, token } = await fixture(); const service = new DurableToyAnalysisService(new MockToyAnalysisProvider(), storage, signer); const first = await service.analyze({ installationToken: token, image, requestId: id(1) }); const cached = await service.analyze({ installationToken: token, image, requestId: id(2) }); expect(cached.suggestedName).toBe(first.suggestedName); expect((await storage.installations.get('ins_1234567890abcdef123456789012345678'))?.betaUsed).toBe(1); });
  it('rejects reuse of an ID with a different fingerprint', async () => { const { storage, signer, token } = await fixture(); const service = new DurableToyAnalysisService(new MockToyAnalysisProvider(), storage, signer); await service.analyze({ installationToken: token, image, requestId: id(3) }); await expect(service.analyze({ installationToken: token, image: { ...image, mockReference: 'unclear_image' }, requestId: id(3) })).rejects.toMatchObject({ code: 'REQUEST_ID_REUSED' }); });
  it('does not invoke the provider when globally disabled', async () => { const { storage, signer, token } = await fixture(); const provider = { analyze: jest.fn() }; const service = new DurableToyAnalysisService(provider, storage, signer); const budget = await storage.budget.get(new Date().toISOString().slice(0, 7)); await storage.budget.update({ ...budget, aiEnabled: false }); await expect(service.analyze({ installationToken: token, image, requestId: id(4) })).rejects.toMatchObject({ code: 'AI_DISABLED' }); expect(provider.analyze).not.toHaveBeenCalled(); });
  it('does not consume successful allowance after provider timeout', async () => { const { storage, signer, token } = await fixture(); const service = new DurableToyAnalysisService(new MockToyAnalysisProvider(), storage, signer); await expect(service.analyze({ installationToken: token, image: { ...image, mockReference: 'provider_timeout' }, requestId: id(5) })).rejects.toMatchObject({ code: 'PROVIDER_TIMEOUT' }); expect((await storage.installations.get('ins_1234567890abcdef123456789012345678'))?.betaUsed).toBe(0); });
});
