import { useState } from 'react';
import { Platform, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { ParentScreen } from '@/components/parent-ui';
import { Banner, PrimaryButton, SecondaryButton } from '@/components/playmap-ui';
import { loadStaffReport, reportToCsv, type AnalyticsReport } from '@/features/analytics/report-service';
import { playmapTheme as theme } from '@/theme/playmap-theme';

const iso = (date: Date) => date.toISOString().slice(0,10);
export default function StaffInsightsRoute() {
  const now = new Date(); const monthAgo = new Date(now); monthAgo.setUTCDate(now.getUTCDate()-30);
  const [start,setStart]=useState(iso(monthAgo)); const [end,setEnd]=useState(iso(now)); const [report,setReport]=useState<AnalyticsReport|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);setError(null);try{setReport(await loadStaffReport({start,end}));}catch(caught){setReport(null);setError(caught instanceof Error?caught.message:'Report could not be loaded.');}finally{setBusy(false);}};
  const exportCsv=async()=>{if(!report)return;setBusy(true);try{await loadStaffReport({start,end},'export');const csv=reportToCsv(report);if(Platform.OS==='web'){const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`pip-insights-${start}-${end}.csv`;anchor.click();URL.revokeObjectURL(url);}else{await Share.share({message:csv,title:`Pip aggregate insights ${start}–${end}`});}}catch{setError('CSV export could not be created.');}finally{setBusy(false);}};
  return <ParentScreen tab="settings"><ScrollView contentContainerStyle={styles.page}><Text accessibilityRole="header" style={styles.title}>Staff insights</Text><Text style={styles.body}>Authorized staff only. UTC date ranges are inclusive. Every view and export is audited.</Text>{error?<Banner message={error} tone="alert"/>:null}<View style={styles.row}><TextInput accessibilityLabel="Start date" onChangeText={setStart} style={styles.input} value={start}/><TextInput accessibilityLabel="End date" onChangeText={setEnd} style={styles.input} value={end}/></View><PrimaryButton disabled={busy} label={busy?'Loading…':'Load report'} onPress={()=>{void load();}}/>{report?<><Metric label="Active households" value={`D ${report.active?.dau??0} · W ${report.active?.wau??0} · M ${report.active?.mau??0}`}/><Metric label="Engagement" value={`${report.engagement?.play_sessions??0} sessions · ${report.engagement?.cleanup_completions??0} cleanups`}/><Text style={styles.heading}>Funnel (distinct households)</Text>{report.funnel?.map(item=><Metric key={item.event_name} label={item.event_name} value={String(item.households)}/>) }<Text style={styles.heading}>Demographics</Text>{report.demographics?.map((item,index)=><Metric key={`${item.kind}-${index}`} label={item.kind} value={item.suppressed?'Insufficient data':`${item.value}: ${item.households}`}/>) }<SecondaryButton label="Export aggregate CSV" onPress={()=>{void exportCsv();}}/></>:null}</ScrollView></ParentScreen>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={styles.metric}><Text style={styles.heading}>{label}</Text><Text style={styles.body}>{value}</Text></View>}
const styles=StyleSheet.create({page:{gap:theme.spacing[16]},title:{color:theme.colors.primaryText,...theme.typography.pageTitle},heading:{color:theme.colors.primaryText,...theme.typography.label},body:{color:theme.colors.secondaryText,...theme.typography.body},row:{flexDirection:'row',gap:theme.spacing[8]},input:{backgroundColor:theme.colors.surface,borderColor:theme.colors.border,borderRadius:theme.radii.medium,borderWidth:1,color:theme.colors.primaryText,flex:1,padding:theme.spacing[12]},metric:{backgroundColor:theme.colors.surface,borderRadius:theme.radii.medium,gap:theme.spacing[4],padding:theme.spacing[12]}});
